global using Pitstop.MaintenanceHistoryAPI.Model;
global using Pitstop.MaintenanceHistoryAPI.Enums;
global using Pitstop.MaintenanceHistoryAPI.DataAccess;
/*global using Pitstop.MaintenanceHistoryAPI.Events;
global using Pitstop.MaintenanceHistoryAPI.Commands;
global using Pitstop.MaintenanceHistoryAPI.Mappers;
global using Pitstop.MaintenanceHistoryAPI.DataAccess;*/
global using Pitstop.Infrastructure.Messaging;
global using Pitstop.Infrastructure.Messaging.Configuration;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Serilog;
global using Microsoft.OpenApi.Models;
global using Microsoft.AspNetCore.Mvc;
global using System.Text.RegularExpressions;
global using Polly;
global using Pitstop.MaintenanceHistoryAPI.Enums;
